set_property SRC_FILE_INFO {cfile:D:/riscv_processor/project_00/project_00.srcs/constrs_1/new/constraints.xdc rfile:../../../project_00.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5   [get_ports clk]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18  [get_ports reset]
